### ISSUE TITLE
IKE是否并不符合模型编辑的需求？

### ISSUE THREAD

**Issue by qizhou000** [Zce1112zslx/IKE#3]
我认为模型编辑的一个关键需求是，一次编辑能永久影响模型对相关知识的回忆。我的理解提出的IKE只是在本次输入之前使用一些前缀(demonstration)来暂时修改模型关于本次输入的回答，一旦结束这次对话，模型并不会保留相应编辑后的记忆。而如果后续的每一次对话，都先输入一长串的“编辑文本”作为前缀，随着顺序编辑次数的增加，一定会超出模型的最长输入上限。即使设置输入长度上限为无限长，对话的计算量会随着编辑次数不断增加。如果一次编辑所需要的demonstration的token长度为100的话，100次编辑之后，一次对话的最短长度就是10000个token，这是不现实的。

**Comment by Zce1112zslx** [comment]
你好~这个问题在我们的discussion这一章节有讨论。在实际应用时，IKE可以类似之前检索式的知识编辑方法[link](https://arxiv.org/pdf/2206.06520.pdf)，将编辑过的知识存储在外部，并对prompt检索可能相关的知识编辑，构造对应的demonstrations，进而不需要把所有demonstrations都拼接在一起。本文主要讨论的是对于检索到的，可能与prompt相关的知识，我们如何设计demonstration，让模型产生应有的行为（更新/维持）。

**Comment by TobiasLee** [comment]
Thanks for your question. There is another influencing factor, i.e., the frequency of knowledge editing. For a relatively stable knowledge update like the president of the US, you can update the model entirely by training on new knowledge facts together. On the other hand, **in-context knowledge editing is more suitable for modifying knowledge that can be changed quickly during a short time**, such as the clubs of soccer players during the transfer window, where injecting permanent changes on the model parameters can be very expensive due to dynamical changes. 

As for the context window restriction, I think it might not be the issue shortly as (i) the supported context window is increasing rapidly, (ii) some retrieval techniques mentioned by @Zce1112zslx can be utilized for referencing key document parts and caching methods like [1] can also be used to pre-compute the knowledge embedding for reducing the computation.

The discussion is also welcome and we hope we can ultimately empower LLMs with real-time knowledge.

[1] Label Words are Anchors: An Information Flow Perspective for Understanding In-Context Learning https://arxiv.org/abs/2305.14160
